GET http://localhost:5066/todos

###

POST http://localhost:5066/todos
Content-Type: application/json

{
    "id": 2,
    "name": "Learn dotNet",
    "dueDate": "2021-12-31",
    "isCompleted": true
}

###

GET http://localhost:5066/todos/2

###

DELETE http://localhost:5066/todos/1

###

GET http://localhost:5066/tasks/1
